---
- hosts: boxes
  sudo: yes
  tasks:
    - action: apt pkg=software-properties-common state=present
    - action: apt_repository repo=ppa:rethinkdb/ppa
#    - apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present
#    - action: apt_repository repo="deb http://get.docker.io/ubuntu docker main"
    - action: apt_repository repo=ppa:chris-lea/node.js
    - action: apt update_cache=yes

    - action: apt pkg=nodejs state=present
    - action: apt pkg=libprotobuf-dev state=present
    - action: apt pkg=rethinkdb state=present
    - command: cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/default.conf creates=/etc/rethinkdb/instances.d/default.conf
    - action: apt pkg=nginx state=present
#    - action: apt pkg=lxc-docker state=present
#    - action: get_url url=http://aphyr.com/riemann/riemann_0.2.2_all.deb dest=/tmp/
#    - action: command dpkg -i /tmp/riemann_0.2.2_all.deb creates=/usr/bin/riemann
#    - action: apt pkg=zookeeperd state=present

# CODE
    - git: repo=https://github.com/icecondor/services.git dest=/home/devops/services
    - git: repo=https://github.com/icecondor/api.git dest=/home/devops/api version=v2

