---
- hosts: web
  become: yes
  become_user: devops
  vars:
    ansible_ssh_user: root

  tasks:
    - name: "git pull icecondor/web master"
      git: repo=https://github.com/icecondor/web.git dest=/home/devops/web version=master
    - name: "npm run build"
      command: npm run build chdir=/home/devops/web
    - name: "git version note"
      shell: git log --pretty=format:'%aI-%h' -n 1 > version chdir=/home/devops/web/build

