---
- hosts: api
  become: yes
  become_user: devops
  vars:
    ansible_ssh_user: root

  tasks:
    - name: "git pull icecondor/api master"
      git: repo=https://github.com/icecondor/api.git dest=/home/devops/api version=master
    - name: "git version note"
      shell: git log --pretty=format:'%aI-%h' -n 1 > version chdir=/home/devops/api
    - name: "npm install (once)"
      command: npm install chdir=/home/devops/api creates=/home/devops/api/node_modules
    - name: "pm2 restart api"
      command: pm2 restart api chdir=/home/devops/api
