---
- hosts: sql
  become_user: root
  vars:
    ansible_ssh_user: root

  tasks:
# PREREQs
    - action: apt pkg=software-properties-common state=present
    - action: apt pkg=build-essential state=present

## REPOS
# RETHINK
    - apt_key: url="http://download.rethinkdb.com/apt/pubkey.gpg" state=present
    - action: apt_repository repo="deb http://download.rethinkdb.com/apt {{ ansible_distribution_release }} main"
# CACHE UPDATE
    - action: apt update_cache=yes

## PACKAGES
# RETHINK
    - action: apt pkg=rethinkdb state=present
    - copy: src=../keys/rethinkdb.conf dest=/etc/rethinkdb/instances.d/default.conf
# GIT
    - action: apt pkg=git state=present

# START
    - name: "restart rethinkdb"
      service:
        name: rethinkdb
        state: restarted

