---
- hosts: api
  become: yes
  vars:
    ansible_ssh_user: root

  tasks:
## PACKAGES
# NODE
    - action: apt pkg=nodejs state=present
# REDIS
    - name: "install redis"
      apt: pkg=redis-server state=present
    - name: "install protobuf"
      apt: pkg=libprotobuf-dev state=present
# RUBY
    - name: "install ruby"
      apt: pkg=ruby-dev state=present
    - command: gem install bundler
# NGINX
    - name: "copying LEGO certs"
      copy: src=../keys/icecondor-lego/ dest=/home/devops/.lego/
      become_user: devops
    - name: "install NGINX"
      apt: pkg=nginx state=present
    - file: state=absent path="/etc/nginx/sites-available"
    - file: state=absent path="/etc/nginx/sites-enabled"
    - copy: src=../keys/nginx.conf dest=/etc/nginx/
    - copy: src=../keys/nginx/_default dest=/etc/nginx/sites/
    - copy: src=../keys/nginx/api.icecondor.com dest=/etc/nginx/sites/
    - copy: src=../keys/index.html dest=/usr/share/nginx/html/
    - name: "reloading nginx"
      systemd: name=nginx state=reloaded

# GIT
    - name: "install git"
      apt: pkg=git state=present

# CODE
    - name: "git clone icecondor/services"
      git: repo=https://github.com/icecondor/services.git dest=/home/devops/services
      become_user: devops
    - name: "git clone icecondor/api"
      git: repo=https://github.com/icecondor/api.git dest=/home/devops/api version=master
      become_user: devops
    - name: "api$ npm install"
      command: npm install chdir=/home/devops/api creates=/home/devops/api/node_modules
      become_user: devops
    - copy: owner=devops src=../keys/settings.json dest=/home/devops/api/settings.json

# START
#    - command: /home/devops/api/node_modules/.bin/pm2 start websockets.js chdir=/home/devops/api
#      sudo: no
#    - command: /home/devops/api/node_modules/.bin/pm2 start sockjs.js chdir=/home/devops/api
#      sudo: no
#    - command: /home/devops/api/node_modules/.bin/pm2 start api.js chdir=/home/devops/api
#      sudo: no

