---
- hosts: web sql
  become_user: root
  gather_facts: no # no python yet
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
    - action: setup

  vars:
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "../keys/digitalocean.root.key"
  tasks:
    - name: "hostname {{inventory_hostname}}"
      hostname:
        name: "{{inventory_hostname}}"

    - name: "/etc/hosts"
      copy:
        src: ../etc-hosts
        dest: /etc/hosts

    - name: "syslog restart"
      service:
        name: rsyslog
        state: restarted

    - name: "create devops unix user"
      user:
        name: devops
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_type: ed25519
