---
- hosts: api sql web
  vars:
    ansible_ssh_user: root

  tasks:
    - name: "hostname {{inventory_hostname}}"
      hostname:
        name: "{{inventory_hostname}}"

    # - name: "/etc/hosts"
    #   copy:
    #     src: ../keys/etc-hosts
    #     dest: /etc/hosts

    - name: "syslog restart"
      service:
        name: rsyslog
        state: restarted

# sudo fallocate -l 1G /swapfile
# sudo chmod 600 /swapfile
# sudo mkswap /swapfile
# echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
# sudo sysctl vm.vfs_cache_pressure=50
# sudo sysctl vm.swappiness=10

    - name: "create devops unix user"
      user:
        name: devops
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_type: ed25519

    - name: "devops authorized_keys"
      copy:
        remote_src: yes
        owner: devops
        src: ~devops/.ssh/id_ed25519.pub
        dest: ~devops/.ssh/authorized_keys

    - name: wait for cloud-init to finish
      command: cloud-init status --wait
      changed_when: false
    - name: "install software-properties-common"
      apt: pkg=software-properties-common state=present
    - name: "install build-essential"
      apt: pkg=build-essential state=present

# REPOS
    - name: "add nginx key"
      apt_key: url="https://nginx.org/keys/nginx_signing.key" state=present
    - name: "add nginx repository {{ ansible_distribution_release }}"
      apt_repository: repo="deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} main" update_cache=no
    - name: "add nodesource key"
      apt_key: url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present
    - name: "add nodesource repository {{ ansible_distribution_release }}"
      apt_repository: repo="deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main" update_cache=no

# APT CACHE UPDATE
    - name: "update apt cache"
      apt: update_cache=yes
