---
- hosts: web api
  vars:
    ansible_ssh_user: root

  tasks:

## PACKAGES
    - action: apt pkg=nodejs state=present
# RUBY
    - name: "install ruby"
      apt: pkg=ruby-dev state=present
    - command: gem install bundler
      args:
        creates: /usr/local/bin/bundle
# NGINX
    - copy: src=../keys/nginx/web.icecondor.com dest=/etc/nginx/sites/
    - name: "reloading nginx"
      systemd: name=nginx state=reloaded
# GIT
    - name: "install git"
      apt: pkg=git state=present
