---
- hosts: api sql web
  become_user: root
  gather_facts: no # no python yet
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
    - action: setup

  vars:
    ansible_ssh_user: root

  tasks:
    - name: "hostname {{inventory_hostname}}"
      hostname:
        name: "{{inventory_hostname}}"

    - name: "/etc/hosts"
      copy:
        src: ../keys/etc-hosts
        dest: /etc/hosts

    - name: "syslog restart"
      service:
        name: rsyslog
        state: restarted

    - name: "create devops unix user"
      user:
        name: devops
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_type: ed25519

    - name: "devops authorized_keys"
      copy:
        remote_src: yes
        src: ~devops/.ssh/id_ed25519.pub
        dest: ~devops/.ssh/authorized_keys

    - name: "devops key retrieve"
      fetch:
        src: ~devops/.ssh/id_ed25519
        dest: "../keys/{{inventory_hostname}}.devops"
