---
- hosts: api
  sudo: yes
  tasks:
# PREREQs
    - action: apt pkg=software-properties-common state=present
    - action: apt pkg=build-essential state=present

## REPOS
    - action: apt_repository repo=ppa:nginx/stable
    - action: apt_repository repo=ppa:chris-lea/node.js
    - action: apt_repository repo="ppa:brightbox/ruby-ng"
# CACHE UPDATE
    - action: apt update_cache=yes

## PACKAGES
# NODE
    - action: apt pkg=nodejs state=present
# REDIS
    - action: apt pkg=redis-server state=present
    - action: apt pkg=libprotobuf-dev state=present
# RUBY
    - action: apt pkg=ruby2.1-dev state=present
    - command: gem install bundler
# NGINX
    - action: apt pkg=nginx state=present
    - copy: src=../keys/api.icecondor.com dest=/etc/nginx/sites-enabled
    - copy: src=../keys/index.html dest=/usr/share/nginx/html/
# GIT
    - action: apt pkg=git state=present
# POSTFIX
    - action: apt pkg=postfix state=present

# CODE
    - git: repo=https://github.com/icecondor/services.git dest=/home/devops/services
      sudo: no
    - git: repo=https://github.com/icecondor/api.git dest=/home/devops/api version=v2
      sudo: no
    - command: npm install chdir=/home/devops/api creates=/home/devops/api/node_modules
      sudo: no
    - copy: owner=devops src=../keys/settings.json dest=/home/devops/api/settings.json

# START
    - command: /home/devops/api/node_modules/.bin/forever start websockets.js chdir=/home/devops/api
    - command: /home/devops/api/node_modules/.bin/forever start api.js chdir=/home/devops/api
