---
- hosts: web
  become: yes
  vars:
    ansible_ssh_user: root

  tasks:

## PACKAGES
# Node.js
    - action: apt pkg=nodejs state=present
# RUBY
    - name: "install ruby"
      apt: pkg=ruby-dev state=present
    - command: gem install bundler
      args:
        creates: /usr/local/bin/bundle
# NGINX
    - name: "nginx sites/web.icecondor.com"
      copy: src=../nginx/sites/web.icecondor.com dest=/etc/nginx/sites/
    - name: "reloading nginx"
      systemd: name=nginx state=reloaded
# GIT
    - name: "install git"
      apt: pkg=git state=present
# CODE
    - name: "git clone icecondor/web"
      git: repo=https://github.com/icecondor/web.git dest=/home/devops/web
      become_user: devops
    - name: "web$ npm install"
      command: npm install chdir=/home/devops/web creates=/home/devops/web/node_modules
      become_user: devops
    - name: "bundle config set path gems"
      command: bundle config set path gems chdir=/home/devops/web
      become_user: devops
    - name: "bundle install"
      command: bundle install --binstubs chdir=/home/devops/web
      become_user: devops
