---
- hosts: sql
  become_user: root
  vars:
    ansible_ssh_user: root

  tasks:
## REPOS
# RETHINK
#    - apt_key: url="http://download.rethinkdb.com/apt/pubkey.gpg" state=present
#    - action: apt_repository repo="deb http://download.rethinkdb.com/apt {{ ansible_distribution_release }} main"
# CACHE UPDATE
#    - action: apt update_cache=yes

## PACKAGES
# RETHINK
#    - action: apt pkg=rethinkdb state=present
#    - copy: src=../keys/rethinkdb.conf dest=/etc/rethinkdb/instances.d/default.conf
# rqlite
    - name: "download rqlite"
      get_url:
        url: https://github.com/rqlite/rqlite/releases/download/v4.3.0/rqlite-v4.3.0-linux-amd64.tar.gz
        dest: /tmp/
    - name: "untar"
      unarchive:
        src: /tmp/rqlite-v4.3.0-linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes
    - name: "copy rqlited to /usr/local/bin/"
      copy:
        src: /tmp/rqlite-v4.3.0-linux-amd64/rqlited
        dest: /usr/local/bin/
        remote_src: yes
    - name: "chmod rqlited"
      file:
        path: /usr/local/bin/rqlited
        mode: 0755
    - name: "copy rqlite to /usr/local/bin/"
      copy:
        src: /tmp/rqlite-v4.3.0-linux-amd64/rqlite
        dest: /usr/local/bin/
        remote_src: yes
    - name: "chmod rqlite"
      file:
        path: /usr/local/bin/rqlite
        mode: 0755
    - name: "copy rqlited unit"
      copy:
        src: ../units/rqlited.service
        dest: /etc/systemd/system/
    - name: systemd enable rqlited
      systemd:
        daemon_reload: yes
        name: rqlited
        enabled: yes
        state: reloaded
# GIT
    - action: apt pkg=git state=present

# START
#    - name: "restart rethinkdb"
#      service:
#        name: rethinkdb
#        state: restarted

