---
- hosts: api sql web
  vars:
    ansible_ssh_user: root
  gather_facts: no # no python yet
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
    - action: setup


  tasks:
    - name: "hostname {{inventory_hostname}}"
      hostname:
        name: "{{inventory_hostname}}"

    - name: "/etc/hosts"
      copy:
        src: ../keys/etc-hosts
        dest: /etc/hosts

    - name: "syslog restart"
      service:
        name: rsyslog
        state: restarted

    - name: "create devops unix user"
      user:
        name: devops
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_type: ed25519

    - name: "devops authorized_keys"
      copy:
        remote_src: yes
        src: ~devops/.ssh/id_ed25519.pub
        dest: ~devops/.ssh/authorized_keys

    - name: "devops key retrieve to ./keys/ssh/{{inventory_hostname}}"
      fetch:
        src: ~devops/.ssh/id_ed25519
        dest: "../keys/ssh/{{inventory_hostname}}" #relative to playbook dir
        flat: yes
# PREREQs
    - name: "install software-properties-common"
      apt: pkg=software-properties-common state=present
    - name: "install build-essential"
      apt: pkg=build-essential state=present

# REPOS
    - name: "add nginx/stable repository"
      apt_repository: repo=ppa:nginx/stable update_cache=no
    - name: "add nodesource key"
      apt_key: url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present
    - name: "add nodesource repository {{ ansible_distribution_release }}"
      apt_repository: repo="deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main" update_cache=no
# CACHE UPDATE
    - name: "update apt cache"
      apt: update_cache=yes
