---
- hosts: web
  become: yes
  become_user: devops
  vars:
    ansible_ssh_user: root

  tasks:
    - name: "git clone icecondor/web"
      git: repo=https://github.com/icecondor/web.git dest=/home/devops/web version=master
    - name: "ruby bundle install"
      command: bundle chdir=/home/devops/web creates=/home/devops/web/gems
    - name: "refresh web/version file with git hash"
      shell: git log --pretty=format:'%h' -n 1 > version chdir=/home/devops/web
    - name: "npm install"
      command: npm install chdir=/home/devops/web creates=/home/devops/web/node_modules
    - name: "grunt web compile"
      shell: PATH=$PATH:./bin ./node_modules/.bin/grunt
      args:
        chdir: /home/devops/web
